image: Visual Studio 2017

before_build:
- nuget restore

build:
  project: CxxSQRunner.sln
  verbosity: minimal
    
after_test:
  - cmd: PublishAndPackage.bat
    
artifacts:
  - path: 'CxxSonarQubeRunner.zip'
    name: CxxSonarQubeRunner
